on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: |
          sudo apt update && sudo apt install python3 python3-pip && sudo pip install cpplint
          cpplint --extensions=c *.c sky_lib/* > cpplint_result.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            cpplint_result.txt
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: |
          git clone https://github.com/google/googletest.git
          cd googletest && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install .
          cd ../../
          mkdir build && cd build
          cmake .. && cmake --build .
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          build/skyscrapers
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/google/googletest.git
          cd googletest && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install .
          cd ../../
          mkdir build && cd build
          cmake .. && cmake --build .
          sudo apt update && sudo apt install valgrind lcov
          valgrind --leak-check=full -s --log-file=valgrind_tests_report.txt ./tests/sky_test
          lcov -t ./tests/sky_test -o coverage.info -c -d sky_lib/ && genhtml -o coverage_report coverage.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/coverage_report/
            build/valgrind_tests_report.txt
