on: push

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Install checking tools
        uses: actions/checkout@v2 
        run: |
          sudo apt update && sudo apt install clang clang-tidy python3 python3-pip && sudo pip install cpplint

      - name: Run checkers
        uses: actions/checkout@v2
        run: |
          cpplint --extensions=c *.c sky_lib/*/* > cpplint_result.txt
          clang-tidy sky_lib/*/* main.c -extra-arg=-std=gnu99 -- -I sky_lib/inc > clang_result.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            cpplint_result.txt
            clang_result.txt
  Build and test:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Install GTest
        uses: actions/checkout@v2 
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install . && cd ../..
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. && cmake --build .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/skyscrapers
      - name: Run tests
        run: |
          sudo apt update && sudo apt install valgrind lcov
          valgrind --leak-check=full -s --log-file=valgrind_tests_report.txt ./tests/sky_test
          lcov -t ./tests/sky_test -o coverage.info -c -d sky_lib/ && genhtml -o coverage_report coverage.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/coverage_report/
            build/valgrind_tests_report.txt
